---
ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1

providers:
  kubernetesCRD:
    allowCrossNamespace: true 

ingressRoute:
  dashboard:
    enabled: true

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

globalArguments:
  - "--api.insecure=true"

deployment:
  replicas: 2

access:
  enabled: true

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - {{ template: "traefik.name" . }}
        topologyKey: failure-domain.beta.kubernetes.io/zone
      




