apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: ${namespace}
spec:
  acme:
    # The ACME server URL
    server: ${acme_server_url}
    # Email address used for ACME registration
    email: ${acme_email}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP01 validations
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: ${api_token_secret_name}
            key: ${api_token_secret_data_key}
    #solvers:
    #- dns01:
    #    cloudflare:
    #      email: my-cloudflare-acc@example.com
    #      apiKeySecretRef:
    #        name: cloudflare-api-key-secret
    #        key: api-key
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: ${k8s_cert_name}
#  namespace: ${namespace}
#spec:
#  secretName: ${k8s_cert_name}-tls
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-prod
#  commonName: ${cloudflare_zone}
#  dnsNames:
#  - ${cloudflare_zone}
#  - '*.${cloudflare_zone}'